### ISSUE TITLE
Build 1.2.1 

### ISSUE THREAD

**Issue by jvmlet** [vbauer/jconditions#1]
Hello 
The  1.2.1 build seems to be broken : https://jitpack.io/com/github/vbauer/jconditions/1.2.1/build.log
Would you please fix it ?
Thanks

**Comment by danielFesenmeyer** [comment]
Same for build 1.2.2.
1.2.0 seems to work.

**Comment by vbauer** [comment]
Sorry, I forgot to close this issue. Everything should be OK with 1.2.2 or 1.2.3
